# Generated by Django 3.1.3 on 2020-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField(default=None)),
                ('username', models.TextField(default=None)),
                ('rol', models.TextField(default=None)),
            ],
        ),
    ]
