# Generated by Django 3.1.3 on 2020-12-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='rol',
            field=models.TextField(choices=[('BOOKLICK_ADMIN', 'Booklick Administrator'), ('UNIVERSITY_ADMIN', 'University Administrator'), ('STUDENT', 'Student'), ('PROFESOR', 'profesor'), ('USER', 'user')], default=None),
        ),
    ]
